### ISSUE TITLE
[PE-D] Screenshot not provided

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S2-CS2103-W16-2/tp#154]
![image.png](https://raw.githubusercontent.com/eugenechiaay/ped/main/files/2525be22-44ac-4028-8b05-6bc99e5c5138.png)

"The GUI similar to the below should appear in a few seconds."

-------------
Labels: `type.DocumentationBug` `severity.VeryLow`
original: eugenechiaay/ped#2

**Comment by chriswengqi** [comment]
#209
