### ISSUE TITLE
[PE-D] Formatting error throughout User Guide

### ISSUE THREAD

**Issue by nus-se-script** [AY2122S2-CS2103-W16-2/tp#155]
Presence of "<&#47;br>" throughout the user guide which distracts readers and make some examples hard to understand
</br>![UG Bug.PNG](https://raw.githubusercontent.com/LowJiaHao99/ped/main/files/857e05fa-f29a-40e9-b6b7-d8bd77899a94.PNG)

-------------
Labels: `severity.Medium` `type.DocumentationBug`
original: LowJiaHao99/ped#1

**Comment by cheehongw** [comment]
duplicate of #173

**Comment by chriswengqi** [comment]
#209
