### ISSUE TITLE
[PE-D] Unable to scroll view 

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S2-CS2103-W16-2/tp#170]
![image.png](https://raw.githubusercontent.com/eugenechiaay/ped/main/files/b48cbcbe-9d05-4fc0-a1e5-fd24c42fb673.png)

-------------
Labels: `type.FeatureFlaw` `severity.Low`
original: eugenechiaay/ped#8

**Comment by cheehongw** [comment]
Probably addressed in #210 and #212
