### ISSUE TITLE
[PE-D] 'Managing Contacts' vs 'Manage Meetings' should be consistent

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S2-CS2103-W16-2/tp#179]
![Screenshot 2022-04-01 at 2.40.40 PM.png](https://raw.githubusercontent.com/viki0526/ped/main/files/1d0441b0-5fd1-4b7f-9265-a60696e625ff.png)

![Screenshot 2022-04-01 at 2.40.33 PM.png](https://raw.githubusercontent.com/viki0526/ped/main/files/9b98cff5-662e-4b7d-b2fc-f81a4dffe96f.png)

-------------
Labels: `severity.Low` `type.DocumentationBug`
original: viki0526/ped#4

**Comment by chriswengqi** [comment]
#209
