### ISSUE TITLE
[PE-D] Duplicate social media in a single person

### ISSUE THREAD

**Issue by nus-se-script** [AY2122S2-CS2103-W16-2/tp#187]
![image.png](https://raw.githubusercontent.com/jessicajacelyn/ped/main/files/920c27ad-9f9d-4a0b-9679-93a4539d34bc.png)

I am able to add multiple of the same social media to the same person.

-------------
Labels: `type.FeatureFlaw` `severity.Medium`
original: jessicajacelyn/ped#8

**Comment by cheehongw** [comment]
Add validation check in before adding duplicate social media:

Social media is considered duplicate if the `platformDescription` is same (case sensitive) and the `platformName` is the same (case insensitive)

E.g: 
```
Telegram: @alexxx
telegram: @alexxx`
```

**Comment by chriswengqi** [comment]
fix `equals` method
