### ISSUE TITLE
[PE-D] invalid commands

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S2-CS2103-W16-2/tp#188]
![image.png](https://raw.githubusercontent.com/eugenechiaay/ped/main/files/146d22a7-7a95-4874-af0d-586fbb82eef2.png)

typing gibberish followed by a command doesnt give an error

-------------
Labels: `type.FeatureFlaw` `severity.Low`
original: eugenechiaay/ped#14

**Comment by cheehongw** [comment]
hmm no idea what is meant by this issue

but from what i can understand from the screenshot, the gibberish is interpreted as a `find` keyword, which is properly handled by the dynamic parser.

however, we can look into what should the behavior of pressing `Enter` key when there is a non command-word in the command box.

**Comment by kavxya** [comment]
Make it more explicit that any other command outside of those defined will be classified as a find command.
