### ISSUE TITLE
[PE-D] Unparsed html tags in UG

### ISSUE THREAD

**Issue by nus-se-script** [AY2122S2-CS2103-W16-2/tp#199]
There are some unparse `</br>` tags across the UG

![bug7.jpg](https://raw.githubusercontent.com/tehkokhoe/ped/main/files/c0af140e-f9f7-4c6e-94bc-89064af03259.jpg)

-------------
Labels: `severity.Low` `type.DocumentationBug`
original: tehkokhoe/ped#7

**Comment by cheehongw** [comment]
Direct link to problem
> https://ay2122s2-cs2103-w16-2.github.io/tp/UserGuide.html#:~:text=add%20n/John%20Doe%20p/91020111%20e/JohnDoe%40outlook.com%20d/Telegram%2C%20%40johnnydoe%20t/friend%3C/br%3E%20add%20n/Betsy%20Crowe%20e/e0123456%40gmail.com%3C/br%3E%20add%20n/Potter
